### ISSUE TITLE
[FRONT_END/ BACK_END] Making ads images full screen on touch and creating an oriented graph stucture on server for implementing geeft history: intent, ui, BaaS calls

### ISSUE THREAD

**Issue by UNOAlterEgo** [meltingpotteam/geeft#19]
Description: Making ads images full screen on touch and creating an oriented graph structure on server for implementing geeft history. The history will be an array of images retrieved trough queries on a linked graph structure.
Requires: layout,ImageViews,fragment,intent, structures, BaaS calls
Status: Coding
Time: 10 Hours

**Comment by vega-dev** [comment]
i've found some visualization errors on the fullscreen image. It result a little bit cropped

**Comment by UNOAlterEgo** [comment]
Yep, I'm working on it

**Comment by UNOAlterEgo** [comment]
Done. Added placeholders too.
