### ISSUE TITLE
[FRONT_END/BACK_END] Categories implementation.

### ISSUE THREAD

**Issue by joseph280** [meltingpotteam/geeft#57]
Description: Adding the Geeft filtered search.
Status: Layout done
Time: 6h
Deadline Day: 02/03/2016

**Comment by UNOAlterEgo** [comment]
Done

**Comment by UNOAlterEgo** [comment]
in testing

**Comment by danybr-dev** [comment]
BUG: When connection is down,a click on each category causes a crash. Check "Snack Bar" in log

**Comment by UNOAlterEgo** [comment]
BUG solved
