### ISSUE TITLE
[FRONT_END/BACK_END] Double user link on manual geeft exchange and feedback check

### ISSUE THREAD

**Issue by danybr-dev** [meltingpotteam/geeft#67]
Description:Double user link on manual geft exchange and feeddback check
Status: /
Time: 10 Hours
Deadline: 6/03/16

**Comment by UNOAlterEgo** [comment]
Use BaasBox.rest().async(Rest.Method.GET, _get_request_, new BassHandler<JsonObject>... , for calling plugins. 
If you prefer you can use the sync method.
_get_request_ is the GET request without the server domain and port, BaasBox already append it for you.
