### ISSUE TITLE
[FRONT_END] Add-Geeft: Interface and basic methods

### ISSUE THREAD

**Issue by vega-dev** [meltingpotteam/geeft#7]
Description: Activity that give the possibility to Upload a new Geeft:
Requires: /
Status: Some interface elements to improve; Code some methods need to add
Time: 15 Hours

**Comment by danybr-dev** [comment]
Remember to add the deadline field to UI

**Comment by UNOAlterEgo** [comment]
(BUG) the app crashes if  I try to add a new gift when the user doesn't take a pic

**Comment by danybr-dev** [comment]
Another fields to add in UI is category and type
