### ISSUE TITLE
[FRONT_END] Geeft Card Object: interface cleaning and listener readaptation  

### ISSUE THREAD

**Issue by vega-dev** [meltingpotteam/geeft#8]
Description: some problem on click listeners and interface adaptetin errors
Requires: /
Status: Some interface elements to improve; Code some methods need to modify
Time: 7 Hours

**Comment by UNOAlterEgo** [comment]
For the onClickListener just add them on the ViewHolder costructor, I didn't do it cause i didn't know which buttons we are going to use.
I can't understand what u mean for adaptetin problems, explain in detail
